{% extends "template/Dockerfile.global.sh.twig" %}

{% block image_variables_sw_currency %}
{% endblock %}

{% block image_variables_mysql %}
{% endblock %}

{% block base_xdg %}
{% endblock %}
    
{% block components_mysql %}
{% endblock %}

{% block components_adminer %}
{% endblock %}

{% block components_mailcatcher %}
{% endblock %}

{% block components_pimpmylog %}
{% endblock %}

{% block assets_install_58shuwei6 %}
{% endblock %}

{% block shuwei %}
{% endblock %}

{% block shuwei_tools_dev_cli %}
{% endblock %}