{% extends "template/Dockerfile.global.sh.twig" %}

{% block image_before %}

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak 

RUN echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src https://mirrors.ustc.edu.cn/ubuntu/ jammy main restricted universe multiverse"  >> /etc/apt/sources.list && \
    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src https://mirrors.ustc.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \

    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src https://mirrors.ustc.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src https://mirrors.ustc.edu.cn/ubuntu/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \

    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy-proposed main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src https://mirrors.ustc.edu.cn/ubuntu/ jammy-proposed main restricted universe multiverse" >> /etc/apt/sources.list
{% endblock %}

{% block shuwei_install %}

## ***********************************************************************
##  INSTALL SHUWEI
## ***********************************************************************
RUN git clone --branch={{ shuwei.platform.branch }} https://github.com/58shuwei/platform /var/www/platform && \
    cp -a /var/www/platform/. /var/www/html/ && \
    rm -rf /var/www/platform && \
    cd /var/www/html && \
    composer install
{% endblock %}

{% block shuwei_prepare %}
{% set env_file = '/var/www/html/.env' %}
{% set psh_override_file = '/var/www/html/.psh.yaml.override' %}

RUN echo "APP_ENV=dev" >> {{ env_file }} && \
    echo "APP_SECRET=1" >> /{{ env_file }} && \
    echo "INSTANCE_ID=1" >> {{ env_file }} && \
    echo "DATABASE_URL=mysql://{{ db.user }}:{{ db.pwd }}@{{ db.host }}:{{ db.port }}/{{ db.database }}" >> {{ env_file }} && \
    echo "APP_URL={{ shuwei.url }}" >> {{ env_file }} && \
    echo "MAILER_URL=smtp://localhost:1025" >> {{ env_file }} && \
    echo "COMPOSER_HOME=/var/www/html/var/cache/composer" >> {{ env_file }} && \
    echo "const:" >> {{ psh_override_file }} && \
    echo '     APP_ENV: "dev"' >> {{ psh_override_file }} && \
    echo '     APP_URL: "{{ shuwei.url }}"' >> {{ psh_override_file }} && \
    echo '     DB_HOST: "{{ db.host }}"' >> {{ psh_override_file }} && \
    echo '     DB_PORT: "{{ db.port }}"' >> {{ psh_override_file }} && \
    echo '     DB_NAME: "{{ db.database }}"' >> {{ psh_override_file }} && \
    echo '     DB_USER: "{{ db.user }}"' >> {{ psh_override_file }} && \
    echo '     DB_PASSWORD: "{{ db.pwd }}"' >> {{ psh_override_file }}

RUN service mysql start && \
    # install shuwei by
    # using the official psh command
    cd /var/www/html && ls -la && \
    export COMPOSER_HOME="/var/www/.composer" && \
    php ./bin/shuwei system:install --drop-database --create-database -f --basic-setup && \
    composer run init:js && \
    composer run build:js:admin && \
    chown www-data:www-data /var/www/html/config/jwt/* 

{% endblock %}


{% block shuwei_dev %}
{# dont do anything in here, no dev prepare stuff#}
{% endblock %}
