{% extends "template/assets/assets/scripts/makefile.twig" %}


{% block watcher_admin %}
watch-admin: ## starts watcher for admin at {{ shuwei.url }}:8888
	cd /var/www/html && PROJECT_ROOT=/var/www/html APP_URL={{ shuwei.url }} ESLINT_DISABLE=true PORT=8888 HOST=0.0.0.0 ENV_FILE=/var/www/html/.env npm run --prefix vendor/shuwei/platform/src/Administration/Resources/app/administration/ dev
{% endblock %}


{% block build_admin %}
{% endblock %}


{% block contribute_pull %}
# ---------------------------------------------------------------------------------------------
pull: ## pulls the latest github version and installs everything again
	cd /var/www/html && git pull
	cd /var/www/html/platform && git pull
	cd /var/www/html && ./psh.phar install
{% endblock %}
